DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12777
DEBUG:git.cmd:Popen(['git', 'add', '--all'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch-check'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=False, shell=None, istream=<valid stream>)
DEBUG:git.cmd:Popen(['git', 'cat-file', '--batch'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=False, shell=None, istream=<valid stream>)
DEBUG:git.cmd:Popen(['git', 'push', '--porcelain', 'origin'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=True, shell=None, istream=None)
DEBUG:root:2021-10-17 18:06:35.697128
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12777
DEBUG:root:2021-10-17 18:21:36.781637
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 13001
DEBUG:root:2021-10-17 18:44:10.843886
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 13001
DEBUG:root:2021-10-17 18:59:12.463138
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 13001
DEBUG:root:2021-10-17 19:14:13.592633
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 19:29:14.762908
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 19:32:51.328645
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 19:47:52.571191
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 20:02:53.754086
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 20:17:54.900314
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12773
DEBUG:root:2021-10-17 20:32:56.122868
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12773
DEBUG:root:2021-10-17 20:47:58.881843
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12773
DEBUG:root:2021-10-17 21:03:00.433664
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12773
DEBUG:root:2021-10-17 21:18:01.747114
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12771
DEBUG:root:2021-10-17 21:33:02.990841
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12771
DEBUG:root:2021-10-17 21:48:04.427754
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12771
DEBUG:root:2021-10-17 22:03:05.694020
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12771
DEBUG:root:2021-10-17 22:18:07.104566
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 22:33:09.044003
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 22:48:11.645412
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 23:03:12.792127
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12772
DEBUG:root:2021-10-17 23:18:13.897614
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12770
DEBUG:root:2021-10-17 23:33:15.094376
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12770
DEBUG:root:2021-10-17 23:48:16.269791
INFO:root:2021-10-18 00:03:16.924167
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 00:18:17.908866
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 00:33:18.672225
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 00:48:19.438742
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 01:03:20.203338
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 01:18:20.919221
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 01:33:21.723010
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 01:48:22.586872
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 02:03:23.351848
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 02:18:24.132583
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 02:33:25.001770
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 02:48:26.064029
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 03:03:26.811901
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 03:18:27.596192
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 03:33:28.552431
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 03:48:29.398930
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 04:03:30.261402
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 04:18:31.022698
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 04:33:31.839423
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 04:48:32.668623
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 05:03:33.698981
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 05:18:34.486078
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 05:33:35.332850
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 05:48:36.075644
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 06:03:36.914920
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 06:18:37.655632
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 06:33:38.487485
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 06:48:39.286265
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 07:03:40.118541
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 07:18:41.011333
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 07:33:42.113608
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 07:48:42.959144
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 08:03:43.932907
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 08:18:44.739715
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 08:33:45.565830
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 08:48:46.592671
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 09:03:47.429534
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 09:18:48.216900
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
INFO:root:2021-10-18 09:28:44.272454
ERROR:root:
Traceback (most recent call last):
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/main_scraper.py", line 39, in <module>
    temperature_obj.fetch() #il y a un bug dans la fct donc je le fetch  chaque fois
  File "/home/pi/GIF-4101_equipe_3_projet/Data_Scraper/temperature_fetch.py", line 44, in fetch
    self.heure = hourly_data[0]
IndexError: list index out of range
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): www.msss.gouv.qc.ca:80
DEBUG:urllib3.connectionpool:http://www.msss.gouv.qc.ca:80 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.msss.gouv.qc.ca:443
DEBUG:urllib3.connectionpool:https://www.msss.gouv.qc.ca:443 "GET /professionnels/statistiques/documents/urgences/Releve_horaire_urgences_7jours.csv HTTP/1.1" 200 12663
DEBUG:git.cmd:Popen(['git', 'pull', '-v', 'origin'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=True, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'add', '--all'], cwd=/home/pi/GIF-4101_equipe_3_projet, universal_newlines=False, shell=None, istream=None)
